from typing import Protocol

class Neo4jLabelAssigner(Protocol):
    def assign_label(self, geometry_node) -> str:
        ...

class Neo4jRevitLabelAssigner:
    def assign_label(self, category) -> str:
        revit_labels_to_query_mapping = {
            "Abutments" : "Abutment",
            "Air Terminals" : "AirTerminal",
            "Analysis Display Style": "AnalysisDisplayStyle",
            "Analysis Results": "AnalysisResult",
            "Areas": "Area",
            "Audio Visual Devices": "AudioVisualDevice",
            "Bearings": "Bearing",
            "Bridge Cables": "BridgeCable",
            "Bridge Decks": "BridgeDeck",
            "Bridge Flaming": "BridgeFlaming",
            "Cable Tray Fittings": "CableTrayFitting",
            "Cable Tray Runs": "CableTrayRun",
            "Cable Trays": "CableTray",
            "Casework": "Casework",
            "Ceilings": "Ceiling",
            "Columns": "Column",
            "Communication Devices": "CommunicationDevice",
            "Conduit Fittings": "ConductFitting",
            "Conduit Runs": "ConductRun",
            "Conduits": "Conduit",
            "Coordination Model": "CoordinationModel",
            "Curtain Grids": "CurtainGrid",
            "Curtain Panels": "CurtainPanel",
            "Curtain Systems": "CurtainSystems",
            "Curtain Wall Mullions": "CurtainWallMullion",
            "Data Devices": "DataDevice",
            "Detail Items": "DetailItem",
            "Doors": "Door",
            "Duct Accessories": "DuctAccessory",
            "Duct Fittings": "DuctFitting",
            "Duct Insulations": "DuctInsulation",
            "Duct Linings": "DuctLining",
            "Duct Placeholders": "DuctPlaceholder",
            "Duct Systems": "DuctSystem",
            "Ducts": "Duct",
            "Electrical Circuits": "ElectricalCircuit",
            "Electrical Equipment": "ElectricalEquipment",
            "Electrical Fixtures": "ElectricalFixture",
            "Entourage": "Entourage",
            "Expansion Joints": "ExpansionJoint",
            "Filled region": "FilledRegion",
            "Fire Alarm Devices": "FireAlarmDevice",
            "Fire Protection": "FireProtection",
            "Flex Ducts": "FlexDuct",
            "Flex Pipes": "FlexPipe",
            "Floors": "Floor",
            "Food Service Equipment": "FoodServiceEquipment",
            "Furniture": "Furniture",
            "Furniture Systems": "FurnitureSystem",
            "Generic Models": "GenericModel",
            "Grids": "Grid",
            "Hardscape": "Hardscape",
            "HVAC Zones": "HVACZone",
            "Imports in Families": "ImportInFamilies",
            "Lighting Devices": "LightingDevice",
            "Lighting Fixtures": "LightingFixtures",
            "Lines": "Line",
            "Masking Region": "MaskingRegion",
            "Mass": "Mass",
            "Mechanical Control Devices": "MechanicalControlDevice",
            "Mechanical Equipment": "MechanicalEquipment",
            "Medical Equipment": "MedicalEquipment",
            "MEP Ancillary Framing": "MEPAncillaryFraming",
            "MEP Fabrication Containment": "MEPFabricationContainment",
            "MEP Fabrication Ductwork": "MEPFabricationDuctwork",
            "MEP Fabrication Ductwork Stiffeners": "MEPFabricationDuctworkStiffener",
            "MEP Fabrication Hangers": "MEPFabricationHanger",
            "MEP Fabriacation Pipework": "MEPFabricationPipework",
            "Nurse Call Devices": "NurseCallDevice",
            "Parking": "Parking",
            "Parts": "Part",
            "Piers": "Pier",
            "Pipe Accessories": "PipeAccessory",
            "Pipe Fittings": "PipeFitting",
            "Pipe Insulations": "PipeInsulation",
            "Pipe Placeholders": "PipePlaceholder",
            "Pipe Segments": "PipeSegment",
            "Pipes": "Pipe",
            "Piping Systems": "PipingSystem",
            "Planting": "Planting",
            "Plumbing Equipment": "PlumbingEquipment",
            "Plumbing Fixtures": "PlumbingFixture",
            "Point Clouds": "PointCloud",
            "Project Information": "ProjectInformation",
            "Railings": "Railing",
            "Ramps": "Ramp",
            "Raster Images": "RasterImage",
            "Roads": "Road",
            "Roofs": "Roof",
            "Rooms": "Room",
            "Routing Preferences": "RountingPreference",
            "Security Devices": "SecurityDevice",
            "Shaft Openings": "ShaftOpening",
            "Sheet Collections": "SheetCollection",
            "Sheets": "Sheet",
            "Signage": "Signage",
            "Site": "Site",
            "Spaces": "Space",
            "Specialty Equipment": "SpecialtyEquipment",
            "Sprinklers": "Sprinkler",
            "Stairs": "Stair",
            "Structural Area Reinforcement": "StructuralAreaReinforcement",
            "Structural Beam Systems": "StructuralBeamSystem",
            "Structural Columns": "StructuralColumn",
            "Structural Connections": "StructuralConnection",
            "Structural Fabric Areas": "StructualFabricArea",
            "Structural Fabric Reinforcement": "StructuralFabricReinforcement",
            "Structural Foundations": "StructuralFoundations",
            "Structural Framing": "StructuralFraming",
            "Structural Path Reinforcement": "StructuralPathReinforement",
            "Structural Rebar": "StructuralRebar",
            "Structural Rebar Couplers": "StructuralRebarCoupler",
            "Structural Stiffeners": "StructuralStiffeners",
            "Structural Tendons": "StructuralTendons",
            "Structural Trusses": "StructuralTrusses",
            "Switch System": "StructuralSystem",
            "Telephone Devices": "TelephoneDevices",
            "Temporary Structures": "TemporaryStructures",
            "Topography": "Topography",
            "Topsolid": "Topsolid",
            "Vertical Circulation": "VerticalCirculation",
            "Walls": "Wall",
            "Windows": "Window",
            "Wires": "Wire"
        }

        return revit_labels_to_query_mapping[category]

class Neo4jIfcLabelAssigner:
    def assign_label(self, category) -> str:
        return category